database:
  dialect: sqlite
  synchronize: true
  storage: "./__tests__/sqlite.storage"

auth:
  secret: teste

email:
  host: smtp.mailtrap.io
  username: af9c948b78b1a1
  password: 9ffc61ed7dd98e
  port: 2525
