database:
  dialect: postgres
  host: localhost
  port: 5432
  username: docker
  password: docker
  database: f3desk
  synchronize: false

auth:
  secret: teste

email:
  host: smtp.mailtrap.io
  port: 2525
  username: af9c948b78b1a1
  password: 9ffc61ed7dd98e
